config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :public do

    root to: 'homes#top'
    get "about", to: 'homes#about'

    resources :users, only: [:show, :edit, :update]
    resources :rooms, only: [:index, :show]
    resources :room_accesses, only: [:create, :update]
    resources :chat_logs, only: [:create]
    resources :study_records do
      member do 
        patch :finish
        patch :post
      end
    end
    resources :study_intervals, only: [:index, :create, :update, :destroy]
    resources :study_categories, only: [:index]
    resources :study_themes, only: [:index,:create, :edit, :update]
    resources :stamps, only: [:index]
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :update, :destroy]
    resources :follows, only: [:create, :destroy]

  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat_log.rb
class ChatLog < ApplicationRecord
  belongs_to :room
  belongs_to :user
  belongs_to :stamp
  validates :message, presence: true, length: { maximum: 250}
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :study_record

  validates :comment_body, presence: true, length: { maximum: 250 }
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followee, class_name: "User"

  validates :followee_id, uniqueness: { scope: :follower_id }
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :study_record

  validates :user_id, uniqueness: { scope: :study_record_id }
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :room_accesses, dependent: :destroy
  has_many :chat_logs, dependent: :destroy
  has_many :study_records, dependent: :destroy
end

app/models/room_access.rb
class RoomAccess < ApplicationRecord
  belongs_to :room
  belongs_to :user
  belongs_to :study_theme

  enum study_status: {
    waiting:  0,
    studying: 1,
    paused:   2,
    finished: 3
  }

  enum exit_type: {
    normal:  0,
    forced: 1,
    timeout:   2,
  }

end
 

app/models/stamp.rb
class Stamp < ApplicationRecord
  has_many :chat_logs, dependent: :destroy

  has_one_attached :stamp_image

  validates :stamp_name, presence: true, uniqueness: true, length: { maximum: 10 }
end

app/models/study_category.rb
class StudyCategory < ApplicationRecord
  has_many :study_themes, dependent: :destroy

  validates :category_title, presence: true, uniqueness: true, length: { maximum: 20 }
  validates :category_body, length: { maximum: 100 }
end

app/models/study_interval.rb
class StudyInterval < ApplicationRecord
  belongs_to :study_record
end

app/models/study_record.rb
class StudyRecord < ApplicationRecord
  has_many :study_intervals, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  belongs_to :user
  belongs_to :room
  belongs_to :study_theme
  
  validates :record_body, length: { maximum: 500 }
end

app/models/study_theme.rb
class StudyTheme < ApplicationRecord
  has_many :room_accesses
  has_many :study_records
  belongs_to :user
  belongs_to :study_category

  validates :theme_title, presence: true, uniqueness:{ scope: :user_id }, length: { maximum: 20 }
  validates :theme_body, length: { maximum: 100 }

  enum theme_color: {
    red:    0, 
    orange: 1, 
    yellow: 2, 
    green:  3, 
    blue:   4, 
    purple: 5, 
    pink:   6, 
    brown:  7, 
    black:  8
  }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :room_accesses, dependent: :destroy
  has_many :chat_logs, dependent: :destroy
  has_many :study_records, dependent: :destroy
  has_many :study_themes, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :active_relationships, class_name: "Follow", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Follow", foreign_key: "followee_id", dependent: :destroy
  
  has_one_attached :user_image
  
  validates :name, presence: true, uniqueness: true, length: { maximum: 20}

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    public_user_path(resource)
  end

  def after_sign_out_path_for(resource)
    public_root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :name])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>COPOMO</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/8edf93cddf.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column min-vh-100 <%= controller_name %>-<%= action_name %>">
    <header>
      <div class = "container-fluid h-100">
        <div class = "row h-100">
          <div class = "col-4 h-100 px-0 py-0"> 
            <%= link_to public_root_path do %>
              <%= image_tag "copomo_logo_t2", style: "height: 100%;" %>
            <% end %>
          </div>
          <div class = "col-8 px-0 py-0">
            <ul class = "header-list d-flex list-unstyled h-100 mb-0 justify-content-end align-items-center">
              <% if user_signed_in? %>
                <li class = "header-item">
                  <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
                </li>
                <li class = "h-100">
                  <%= link_to "マイページ", public_user_path(current_user.id) %>
                </li>
                <li class = "h-100">
                  <%= link_to "学習ルーム", public_rooms_path %>
                </li>
                <li class = "h-100">
                  <%= link_to "タイムライン",public_study_records_path %>
                </li>
              <% else %>
                <li class = "h-100">
                  <%= link_to "新規登録", new_user_registration_path %>
                </li>
                <li class = "h-100">
                  <%= link_to "ログイン", new_user_session_path %>
                </li>
              <% end %>
              <li class = "h-100">
                <%= link_to "COPOMOとは", public_about_path %>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </header>

    <main class="flex-fill d-flex">
      <%= yield %>
    </main>

    <footer class="d-flex  align-items-center justify-content-center">
      <p class="m-0">&copy; 2026 COPOMO.</p>
    </footer>

  </body>
</html>